import { useEffect, useMemo, useState } from 'react'
import { MapView } from './MapView'
import { dedupeRoutes, estimateKmFromMinutes, formatDistance, formatTime, nearestProgress, nextTurn, type Point, type Route } from './lib'
type Screen='welcome'|'planner'|'choices'|'walk'
const DEFAULT:Point=[-4.4816,54.1506] // Douglas, Isle of Man
export function LooperApp(){const [screen,setScreen]=useState<Screen>('welcome'),[start,setStart]=useState<Point>(DEFAULT),[position,setPosition]=useState<Point>(),[locationState,setLocationState]=useState(''),[mode,setMode]=useState<'distance'|'time'>('distance'),[unit,setUnit]=useState<'km'|'mi'>('km'),[amount,setAmount]=useState('4'),[preference,setPreference]=useState('balanced'),[routes,setRoutes]=useState<Route[]>([]),[selected,setSelected]=useState<Route>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[muted,setMuted]=useState(false),[offRoute,setOffRoute]=useState(false),[progress,setProgress]=useState(0)
 const requestLocation=()=>{if(!navigator.geolocation){setLocationState('Location is not available in this browser.');return}setLocationState('Finding your location…');(navigator.geolocation.getCurrentPosition as any)((p:any)=>{const point:Point=[p.coords.longitude,p.coords.latitude];setStart(point);setPosition(point);setLocationState('');setScreen('planner')},(e:any)=>setLocationState(e.code===1?'Location permission was declined. Choose a start point on the map.':'We could not get a location. Choose a start point on the map.'),{enableHighAccuracy:true,timeout:12000,maximumAge:15000})}
 const distanceKm=useMemo(()=>mode==='time'?estimateKmFromMinutes(Number(amount)):unit==='mi'?Number(amount)/.621371:Number(amount),[mode,unit,amount])
 const valid=mode==='time'?Number(amount)>=15&&Number(amount)<=240:distanceKm>=1&&distanceKm<=20
 async function findRoutes(){if(!valid){setError(mode==='time'?'Choose 15 minutes to 4 hours.':'Choose a loop between 1 and 20 km.');return}if(!navigator.onLine){setError('You’re offline. Route generation needs a connection; saved walks are still available.');return}setBusy(true);setError('');try{const r=await fetch('/api/routes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({start:{lng:start[0],lat:start[1]},inputMode:mode,distanceKm:mode==='distance'?distanceKm:undefined,minutes:mode==='time'?Number(amount):undefined,preference})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Routes are unavailable right now.');const choices=dedupeRoutes(data.routes);if(!choices.length)throw new Error('No loops found from this point. Try a different distance or start point.');setRoutes(choices);setScreen('choices');if(choices.length<3)setError(`We found ${choices.length} loop${choices.length===1?'':'s'} from here.`)}catch(e){setError(e instanceof Error?e.message:'Routes are unavailable right now.')}finally{setBusy(false)}}
 function beginWalk(r:Route){setSelected(r);setScreen('walk');localStorage.setItem('looper-route',JSON.stringify(r))}
 useEffect(()=>{if(screen!=='walk'||!navigator.geolocation||!selected)return;let bad=0;const id=(navigator.geolocation.watchPosition as any)((p:any)=>{if(p.coords.accuracy>100){setLocationState('Waiting for a more accurate location…');return}setLocationState('');const point:Point=[p.coords.longitude,p.coords.latitude];setPosition(point);const match=nearestProgress(point,selected.geometry.coordinates);setProgress(old=>Math.max(old,match.distanceAlong));bad=match.distanceToRoute>55?bad+1:0;setOffRoute(bad>=3)},undefined,{enableHighAccuracy:true,timeout:15000,maximumAge:5000});return()=>navigator.geolocation.clearWatch(id)},[screen,selected])
 const turn=selected&&nextTurn(selected,progress), remaining=selected?Math.max(0,selected.distanceMeters-progress):0
 return <main>{screen==='welcome'&&<section className="welcome"><div className="loop-mark">↻</div><p className="eyebrow">a walk with a way back</p><h1>Looper</h1><p className="lede">Find a walk that brings you back.</p><div className="welcome-actions"><button className="primary" onClick={requestLocation}>⌖ Use my location</button><button className="secondary" onClick={()=>setScreen('planner')}>Choose on map</button></div>{locationState&&<p className="notice">{locationState}</p>}<p className="privacy">Your location stays on your device.</p><button className="help" onClick={()=>setLocationState('Keep Looper open while walking for live guidance. Guidance may pause when your phone is locked.')}>How live guidance works</button></section>}
 {screen!=='welcome'&&<><MapView start={start} routes={routes} selected={selected?.id} position={position} onPoint={setStart}/>{screen==='planner'&&<section className="sheet planner"><div className="handle"/><p className="eyebrow">start point</p><h2>Where shall we loop?</h2><p className="quiet">Tap the map or drag around to set your starting point.</p><div className="seg"><button className={mode==='distance'?'on':''} onClick={()=>setMode('distance')}>Distance</button><button className={mode==='time'?'on':''} onClick={()=>setMode('time')}>Time</button></div><div className="value-row"><input aria-label={mode==='distance'?'Distance':'Minutes'} value={amount} inputMode="decimal" onChange={e=>setAmount(e.target.value)}/>{mode==='distance'?<div className="unit"><button className={unit==='km'?'on':''} onClick={()=>setUnit('km')}>km</button><button className={unit==='mi'?'on':''} onClick={()=>setUnit('mi')}>mi</button></div>:<span>minutes</span>}</div><div className="prefs">{[['balanced','Balanced'],['quiet','Quieter'],['direct','Direct']].map(([v,l])=><button key={v} className={preference===v?'on':''} onClick={()=>setPreference(v)}>{l}</button>)}</div>{error&&<p className="notice">{error}</p>}<button disabled={busy} className="primary find" onClick={findRoutes}>{busy?'Finding local loops…':'Find my loops'}</button><button className="centre" onClick={requestLocation}>Centre on me</button></section>}
 {screen==='choices'&&<section className="sheet choices"><div className="handle"/><div className="sheet-title"><div><p className="eyebrow">your choices</p><h2>Pick a loop</h2></div><button className="text" onClick={()=>setScreen('planner')}>Edit</button></div>{error&&<p className="notice">{error}</p>}{routes.map((r,i)=><article className="route-card" key={r.id} onClick={()=>setSelected(r)}><i style={{background:['#ef6b55','#206a77','#80679d'][i]}}/><div><strong>{r.name}</strong><p>{formatDistance(r.distanceMeters,unit)} · {formatTime(r.durationSeconds)} · {Math.abs(r.targetDifferencePercent)}% {r.targetDifferencePercent<0?'shorter':'longer'}</p></div><button className="choose" onClick={e=>{e.stopPropagation();beginWalk(r)}}>Choose</button></article>)}</section>}
 {screen==='walk'&&selected&&<section className="walk-ui"><header><button onClick={()=>setScreen('choices')}>End walk</button><button onClick={requestLocation}>⌖</button><button onClick={()=>setMuted(!muted)}>{muted?'Muted':'Voice on'}</button></header>{locationState&&<p className="gps">{locationState}</p>}{offRoute?<div className="guidance warning"><b>You’re off the planned loop</b><p>Get back to the route, or finish this walk.</p><button className="primary" onClick={()=>setOffRoute(false)}>Show route from here</button><button className="text" onClick={()=>setScreen('choices')}>End walk</button></div>:<div className={'guidance '+(turn&&turn.distanceAway<20?'close':'')}><span className="arrow">↰</span><div><p className="eyebrow">{turn?`${Math.round(turn.distanceAway)} m ahead`:'Almost home'}</p><h2>{turn?.instruction||'You’re back where you started.'}</h2><p>{formatDistance(remaining,unit)} remaining · about {formatTime(remaining/selected.distanceMeters*selected.durationSeconds)}</p></div></div>}</section>}</>}</main>}
export function App(){return <LooperApp/>}
